// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uioescbduasfwkpcvtyn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVpb2VzY2JkdWFzZndrcGN2dHluIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0MTEyNjMsImV4cCI6MjA2MDk4NzI2M30.IX4w1ABoqJ8c-9gLFrUaLREuAYnPTdOCFebizub8I4s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);